name: hms_video_plugin_example
description: Demonstrates how to use the hms_video_plugin plugin.

publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hms_video_plugin:
    path: ../

  hms_room_kit: 1.2.0

  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
