name: hms_video_plugin
description: Integrate virtual backgrounds, blur backgrounds effects in your Flutter app with the 100ms Video Plugin.
version: 0.1.0
homepage: https://www.100ms.live/
repository: https://github.com/100mslive/flutter-video-plugin
issue_tracker: https://github.com/100mslive/flutter-video-plugin/issues
documentation: https://www.100ms.live/docs

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  hmssdk_flutter:
    path: ../100ms-flutter/packages/hmssdk_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: live.hms.hms_video_plugin
        pluginClass: HmsVideoFilterPlugin
      ios:
        pluginClass: HmsVideoFilterPlugin

  assets:
    - lib/assets/sdk-versions.json
